-- ============================================================
-- Chop — 003_seed_ingredients.sql
--
-- 217 canonical ingredients, Australian products and pack sizes.
-- Macros are left null; they get loaded from AFCD in phase 6.
--
-- ml_per_each is the YIELD of one whole item:
--   lemon  -> 45 ml juice
--   garlic -> 5 ml crushed (one clove ~ 1 tsp)
-- This is how "juice of 1 lemon", "1 tbsp lemon juice" and
-- "juice of 1/2 lemon" all resolve to the same canonical row.
--
-- divisible = true  -> buy the shortfall (weighed goods)
-- divisible = false -> buy whole packs (cans, jars, bottles)
-- ============================================================

insert into ingredients (
  canonical_name, aliases, category, default_unit,
  g_per_ml, g_per_each, ml_per_each,
  is_staple, shelf_life_days,
  purchase_unit, pack_size, divisible,
  is_meat, is_fish, is_dairy, is_gluten
) values
  ('brown onion', array['onion','yellow onion','brown onions','diced onion'], 'produce', 'g', null, 150, null, true, 30, 'g', 1000, true, false, false, false, false),
  ('red onion', array['red onions','spanish onion'], 'produce', 'g', null, 140, null, false, 30, 'g', 1000, true, false, false, false, false),
  ('spring onion', array['green onion','green onions','scallion','shallots (green)'], 'produce', 'g', null, 15, null, false, 7, 'each', 1, false, false, false, false, false),
  ('garlic', array['garlic clove','garlic cloves','minced garlic','crushed garlic','garlic head','garlic heads'], 'produce', 'each', null, 3, 5, true, 60, 'each', 1, true, false, false, false, false),
  ('ginger', array['fresh ginger','grated ginger','ginger root'], 'produce', 'g', null, 30, 45, true, 21, 'g', 100, true, false, false, false, false),
  ('lemon', array['lemons','lemon juice','juice of a lemon'], 'produce', 'each', null, 100, 45, true, 21, 'each', 1, true, false, false, false, false),
  ('lime', array['limes','lime juice'], 'produce', 'each', null, 70, 30, false, 21, 'each', 1, true, false, false, false, false),
  ('carrot', array['carrots'], 'produce', 'g', null, 80, null, true, 21, 'g', 1000, true, false, false, false, false),
  ('celery', array['celery stalk','celery stick'], 'produce', 'g', null, 50, null, false, 14, 'each', 1, false, false, false, false, false),
  ('potato', array['potatoes','desiree potato','sebago'], 'produce', 'g', null, 170, null, true, 30, 'g', 2000, true, false, false, false, false),
  ('sweet potato', array['kumara','sweet potatoes'], 'produce', 'g', null, 200, null, false, 21, 'g', 1000, true, false, false, false, false),
  ('tomato', array['tomatoes','truss tomato'], 'produce', 'g', null, 120, null, false, 10, 'g', 1000, true, false, false, false, false),
  ('cherry tomatoes', array['cherry tomato','grape tomatoes'], 'produce', 'g', 0.6, null, null, false, 10, 'g', 250, false, false, false, false, false),
  ('cucumber', array['lebanese cucumber','continental cucumber'], 'produce', 'g', null, 200, null, false, 10, 'each', 1, true, false, false, false, false),
  ('capsicum', array['bell pepper','red capsicum','green capsicum'], 'produce', 'g', null, 160, null, false, 12, 'each', 1, true, false, false, false, false),
  ('red chilli', array['chilli','fresh chilli','birds eye chilli','long red chilli'], 'produce', 'g', null, 10, null, false, 10, 'g', 100, true, false, false, false, false),
  ('broccoli', array['broccoli head','broccoli florets'], 'produce', 'g', null, 350, null, false, 10, 'g', 500, true, false, false, false, false),
  ('cauliflower', array['cauliflower head'], 'produce', 'g', null, 900, null, false, 12, 'each', 1, true, false, false, false, false),
  ('zucchini', array['courgette','zucchinis'], 'produce', 'g', null, 200, null, false, 12, 'g', 500, true, false, false, false, false),
  ('eggplant', array['aubergine'], 'produce', 'g', null, 350, null, false, 10, 'each', 1, true, false, false, false, false),
  ('mushrooms', array['button mushrooms','swiss brown mushrooms','cup mushrooms'], 'produce', 'g', null, 20, null, false, 7, 'g', 500, true, false, false, false, false),
  ('baby spinach', array['spinach','spinach leaves'], 'produce', 'g', 0.15, null, null, false, 6, 'g', 120, false, false, false, false, false),
  ('lettuce', array['cos lettuce','iceberg lettuce','mixed leaves'], 'produce', 'g', null, 400, null, false, 7, 'each', 1, false, false, false, false, false),
  ('cabbage', array['green cabbage','wombok','chinese cabbage'], 'produce', 'g', null, 1000, null, false, 21, 'each', 1, true, false, false, false, false),
  ('bok choy', array['pak choy','baby bok choy'], 'produce', 'g', null, 120, null, false, 6, 'each', 1, false, false, false, false, false),
  ('coriander', array['fresh coriander','cilantro','coriander leaves'], 'produce', 'g', 0.08, null, null, false, 6, 'each', 1, false, false, false, false, false),
  ('parsley', array['flat leaf parsley','italian parsley','continental parsley'], 'produce', 'g', 0.08, null, null, false, 7, 'each', 1, false, false, false, false, false),
  ('basil', array['fresh basil','basil leaves'], 'produce', 'g', 0.06, null, null, false, 5, 'each', 1, false, false, false, false, false),
  ('mint', array['fresh mint','mint leaves'], 'produce', 'g', 0.07, null, null, false, 6, 'each', 1, false, false, false, false, false),
  ('dill', array['fresh dill','dill fronds'], 'produce', 'g', 0.07, null, null, false, 6, 'each', 1, false, false, false, false, false),
  ('thyme', array['fresh thyme'], 'produce', 'g', 0.07, null, null, false, 10, 'each', 1, false, false, false, false, false),
  ('rosemary', array['fresh rosemary'], 'produce', 'g', 0.08, null, null, false, 14, 'each', 1, false, false, false, false, false),
  ('avocado', array['avocados','hass avocado'], 'produce', 'g', null, 200, null, false, 6, 'each', 1, true, false, false, false, false),
  ('apple', array['apples','granny smith','pink lady'], 'produce', 'g', null, 180, null, false, 21, 'g', 1000, true, false, false, false, false),
  ('banana', array['bananas'], 'produce', 'g', null, 120, null, false, 7, 'g', 1000, true, false, false, false, false),
  ('orange', array['oranges','navel orange'], 'produce', 'each', null, 180, 70, false, 21, 'each', 1, true, false, false, false, false),
  ('pumpkin', array['butternut pumpkin','kent pumpkin'], 'produce', 'g', null, 1500, null, false, 30, 'g', 1000, true, false, false, false, false),
  ('green beans', array['beans','french beans'], 'produce', 'g', null, 6, null, false, 8, 'g', 250, true, false, false, false, false),
  ('snow peas', array['mangetout'], 'produce', 'g', null, 4, null, false, 7, 'g', 200, true, false, false, false, false),
  ('corn', array['corn cob','sweet corn'], 'produce', 'each', null, 250, null, false, 10, 'each', 1, false, false, false, false, false),
  ('leek', array['leeks'], 'produce', 'g', null, 250, null, false, 14, 'each', 1, true, false, false, false, false),
  ('shallot', array['eschalot','french shallot'], 'produce', 'g', null, 30, null, false, 30, 'g', 250, true, false, false, false, false),
  ('kale', array['curly kale','tuscan kale'], 'produce', 'g', 0.1, null, null, false, 7, 'each', 1, false, false, false, false, false),
  ('asparagus', array['asparagus spears'], 'produce', 'g', null, 18, null, false, 7, 'g', 250, false, false, false, false, false),
  ('beetroot', array['beets','fresh beetroot'], 'produce', 'g', null, 150, null, false, 21, 'g', 500, true, false, false, false, false),
  ('radish', array['radishes'], 'produce', 'g', null, 20, null, false, 10, 'g', 250, true, false, false, false, false),
  ('fennel', array['fennel bulb'], 'produce', 'g', null, 300, null, false, 12, 'each', 1, true, false, false, false, false),
  ('lemongrass', array['lemon grass','lemongrass stalk'], 'produce', 'each', null, 20, null, false, 14, 'each', 1, false, false, false, false, false),
  ('kaffir lime leaves', array['makrut lime leaves','lime leaves'], 'produce', 'each', null, 1, null, false, 30, 'g', 10, false, false, false, false, false),
  ('bean sprouts', array['beansprouts','mung bean sprouts'], 'produce', 'g', 0.1, null, null, false, 4, 'g', 250, false, false, false, false, false),
  ('chicken thighs', array['boneless skinless chicken thighs','chicken thigh fillets','thigh fillets'], 'meat', 'g', null, 120, null, false, 3, 'g', 1000, true, true, false, false, false),
  ('chicken breast', array['chicken breasts','breast fillet','chicken breast fillet'], 'meat', 'g', null, 200, null, false, 3, 'g', 1000, true, true, false, false, false),
  ('chicken drumsticks', array['drumsticks'], 'meat', 'g', null, 110, null, false, 3, 'g', 1000, true, true, false, false, false),
  ('whole chicken', array['roast chicken','chicken'], 'meat', 'g', null, 1600, null, false, 3, 'each', 1, false, true, false, false, false),
  ('chicken mince', array['ground chicken','minced chicken'], 'meat', 'g', null, null, null, false, 2, 'g', 500, true, true, false, false, false),
  ('pork mince', array['ground pork','minced pork'], 'meat', 'g', null, null, null, false, 2, 'g', 500, true, true, false, false, false),
  ('beef mince', array['ground beef','minced beef','hamburger mince'], 'meat', 'g', null, null, null, true, 2, 'g', 500, true, true, false, false, false),
  ('lamb mince', array['ground lamb','minced lamb'], 'meat', 'g', null, null, null, false, 2, 'g', 500, true, true, false, false, false),
  ('pork belly', array['belly pork'], 'meat', 'g', null, null, null, false, 3, 'g', 1000, true, true, false, false, false),
  ('pork shoulder', array['pork scotch','boston butt'], 'meat', 'g', null, null, null, false, 3, 'g', 1000, true, true, false, false, false),
  ('beef steak', array['porterhouse','scotch fillet','rump steak','sirloin'], 'meat', 'g', null, 250, null, false, 4, 'g', 500, true, true, false, false, false),
  ('beef chuck', array['chuck steak','stewing beef','casserole steak'], 'meat', 'g', null, null, null, false, 4, 'g', 1000, true, true, false, false, false),
  ('lamb shoulder', array['lamb forequarter'], 'meat', 'g', null, null, null, false, 4, 'g', 1000, true, true, false, false, false),
  ('lamb chops', array['lamb cutlets','loin chops'], 'meat', 'g', null, 90, null, false, 3, 'g', 500, true, true, false, false, false),
  ('bacon', array['bacon rashers','streaky bacon','short cut bacon'], 'meat', 'g', null, 25, null, false, 10, 'g', 250, true, true, false, false, false),
  ('chorizo', array['chorizo sausage'], 'meat', 'g', null, 120, null, false, 14, 'each', 1, true, true, false, false, false),
  ('sausages', array['snags','pork sausages','beef sausages'], 'meat', 'g', null, 90, null, false, 4, 'g', 500, true, true, false, false, false),
  ('ham', array['sliced ham','leg ham'], 'meat', 'g', null, null, null, false, 7, 'g', 200, true, true, false, false, false),
  ('prosciutto', array['parma ham'], 'meat', 'g', null, 12, null, false, 14, 'g', 100, true, true, false, false, false),
  ('salmon fillet', array['salmon','atlantic salmon'], 'seafood', 'g', null, 180, null, false, 2, 'g', 300, true, false, true, false, false),
  ('barramundi', array['barra','barramundi fillet'], 'seafood', 'g', null, 180, null, false, 2, 'g', 300, true, false, true, false, false),
  ('white fish fillet', array['snapper','flathead','basa','white fish'], 'seafood', 'g', null, 170, null, false, 2, 'g', 400, true, false, true, false, false),
  ('prawns', array['shrimp','green prawns','raw prawns'], 'seafood', 'g', null, 15, null, false, 2, 'g', 500, true, false, true, false, false),
  ('tinned tuna', array['canned tuna','tuna'], 'seafood', 'g', null, null, null, true, 730, 'g', 95, false, false, true, false, false),
  ('tinned salmon', array['canned salmon'], 'seafood', 'g', null, null, null, false, 730, 'g', 210, false, false, true, false, false),
  ('anchovies', array['anchovy fillets','tinned anchovies'], 'seafood', 'g', null, 4, null, false, 365, 'g', 45, false, false, true, false, false),
  ('squid', array['calamari','calamari rings'], 'seafood', 'g', null, null, null, false, 2, 'g', 500, true, false, true, false, false),
  ('mussels', array['black mussels'], 'seafood', 'g', null, 20, null, false, 2, 'g', 1000, true, false, true, false, false),
  ('fish sauce', array['nam pla','nuoc mam'], 'seafood', 'ml', 1.15, null, null, true, 730, 'ml', 300, false, false, true, false, false),
  ('milk', array['full cream milk','whole milk','dairy milk'], 'dairy', 'ml', 1.03, null, null, true, 10, 'ml', 2000, false, false, false, true, false),
  ('thickened cream', array['double cream','heavy whipping cream','heavy cream','pouring cream'], 'dairy', 'ml', 1.0, null, null, false, 14, 'ml', 300, false, false, false, true, false),
  ('sour cream', array['light sour cream'], 'dairy', 'g', 1.0, null, null, false, 21, 'g', 300, false, false, false, true, false),
  ('butter', array['salted butter','unsalted butter','melted butter'], 'dairy', 'g', 0.911, null, null, true, 60, 'g', 250, false, false, false, true, false),
  ('greek yoghurt', array['greek yogurt','natural yoghurt','plain yoghurt','yogurt','yoghurt'], 'dairy', 'g', 1.03, null, null, true, 21, 'g', 500, false, false, false, true, false),
  ('cheddar cheese', array['tasty cheese','cheddar','grated cheese'], 'dairy', 'g', null, null, null, true, 30, 'g', 500, true, false, false, true, false),
  ('parmesan', array['parmigiano','parmesan cheese','grated parmesan'], 'dairy', 'g', null, null, null, true, 60, 'g', 200, true, false, false, true, false),
  ('mozzarella', array['pizza cheese','fresh mozzarella'], 'dairy', 'g', null, 125, null, false, 21, 'g', 250, true, false, false, true, false),
  ('feta', array['feta cheese','greek feta'], 'dairy', 'g', null, null, null, false, 30, 'g', 200, true, false, false, true, false),
  ('halloumi', array['haloumi'], 'dairy', 'g', null, 180, null, false, 30, 'g', 180, false, false, false, true, false),
  ('ricotta', array['ricotta cheese'], 'dairy', 'g', 1.0, null, null, false, 10, 'g', 250, true, false, false, true, false),
  ('cream cheese', array['philadelphia'], 'dairy', 'g', 1.0, null, null, false, 21, 'g', 250, true, false, false, true, false),
  ('eggs', array['egg','large eggs','free range eggs'], 'dairy', 'each', null, 55, null, true, 28, 'each', 12, false, false, false, false, false),
  ('coconut milk', array['tinned coconut milk','canned coconut milk'], 'pantry', 'ml', 1.0, null, null, true, 730, 'ml', 400, false, false, false, false, false),
  ('coconut cream', array['tinned coconut cream'], 'pantry', 'ml', 1.0, null, null, false, 730, 'ml', 400, false, false, false, false, false),
  ('bread', array['sliced bread','white bread','sourdough','loaf'], 'bakery', 'g', null, 700, null, true, 6, 'each', 1, false, false, false, false, true),
  ('naan bread', array['naan','garlic naan'], 'bakery', 'each', null, 90, null, false, 10, 'each', 4, false, false, false, false, true),
  ('pita bread', array['pita','pitta','flatbread','lebanese bread'], 'bakery', 'each', null, 60, null, false, 10, 'each', 6, false, false, false, false, true),
  ('tortillas', array['wraps','flour tortillas','soft tacos'], 'bakery', 'each', null, 45, null, false, 21, 'each', 8, false, false, false, false, true),
  ('burger buns', array['brioche buns','hamburger buns'], 'bakery', 'each', null, 70, null, false, 7, 'each', 6, false, false, false, false, true),
  ('breadcrumbs', array['panko','panko breadcrumbs','dried breadcrumbs'], 'pantry', 'g', 0.25, null, null, true, 180, 'g', 200, false, false, false, false, true),
  ('dumpling wrappers', array['gow gee wrappers','wonton wrappers','dumpling skins'], 'frozen', 'each', null, 6, null, false, 60, 'each', 30, false, false, false, false, true),
  ('puff pastry', array['frozen puff pastry','pastry sheets'], 'frozen', 'each', null, 175, null, false, 180, 'each', 6, false, false, false, false, true),
  ('olive oil', array['extra virgin olive oil','evoo'], 'pantry', 'ml', 0.918, null, null, true, 540, 'ml', 750, false, false, false, false, false),
  ('vegetable oil', array['canola oil','sunflower oil','neutral oil'], 'pantry', 'ml', 0.92, null, null, true, 540, 'ml', 750, false, false, false, false, false),
  ('avocado oil', '{}', 'pantry', 'ml', 0.918, null, null, false, 365, 'ml', 500, false, false, false, false, false),
  ('sesame oil', array['toasted sesame oil'], 'pantry', 'ml', 0.92, null, null, true, 365, 'ml', 250, false, false, false, false, false),
  ('coconut oil', '{}', 'pantry', 'ml', 0.92, null, null, false, 540, 'ml', 500, false, false, false, false, false),
  ('soy sauce', array['light soy sauce','dark soy sauce','kecap asin'], 'pantry', 'ml', 1.15, null, null, true, 730, 'ml', 500, false, false, false, false, true),
  ('oyster sauce', '{}', 'pantry', 'ml', 1.3, null, null, true, 540, 'ml', 500, false, false, true, false, true),
  ('hoisin sauce', '{}', 'pantry', 'ml', 1.25, null, null, false, 540, 'ml', 250, false, false, false, false, true),
  ('chilli crisp', array['chili crisp','chilli oil','lao gan ma'], 'pantry', 'ml', 0.95, null, null, false, 365, 'ml', 200, false, false, false, false, false),
  ('sriracha', array['sriracha sauce','hot sauce'], 'pantry', 'ml', 1.1, null, null, false, 540, 'ml', 480, false, false, false, false, false),
  ('worcestershire sauce', array['worcester sauce'], 'pantry', 'ml', 1.1, null, null, true, 730, 'ml', 250, false, false, true, false, false),
  ('rice vinegar', array['rice wine vinegar'], 'pantry', 'ml', 1.0, null, null, true, 730, 'ml', 250, false, false, false, false, false),
  ('white vinegar', array['distilled vinegar'], 'pantry', 'ml', 1.0, null, null, true, 730, 'ml', 500, false, false, false, false, false),
  ('balsamic vinegar', array['balsamic'], 'pantry', 'ml', 1.06, null, null, true, 730, 'ml', 250, false, false, false, false, false),
  ('apple cider vinegar', array['acv'], 'pantry', 'ml', 1.0, null, null, false, 730, 'ml', 500, false, false, false, false, false),
  ('dijon mustard', array['dijon'], 'pantry', 'g', 1.05, null, null, true, 365, 'g', 200, false, false, false, false, false),
  ('wholegrain mustard', array['seeded mustard'], 'pantry', 'g', 1.05, null, null, false, 365, 'g', 200, false, false, false, false, false),
  ('tomato paste', array['tomato puree','concentrated tomato paste'], 'pantry', 'g', 1.07, null, null, true, 540, 'g', 140, false, false, false, false, false),
  ('chopped tomatoes', array['tinned tomatoes','canned tomatoes','diced tomatoes','crushed tomatoes'], 'pantry', 'g', 1.0, null, null, true, 730, 'g', 400, false, false, false, false, false),
  ('passata', array['tomato passata','sieved tomatoes'], 'pantry', 'ml', 1.05, null, null, false, 540, 'ml', 700, false, false, false, false, false),
  ('tomato sauce', array['ketchup'], 'pantry', 'ml', 1.1, null, null, true, 540, 'ml', 500, false, false, false, false, false),
  ('mayonnaise', array['mayo','whole egg mayonnaise'], 'pantry', 'g', 0.91, null, null, true, 180, 'g', 400, false, false, false, false, false),
  ('chicken stock', array['chicken broth','chicken stock cube','liquid chicken stock'], 'pantry', 'ml', 1.0, null, null, true, 365, 'ml', 1000, false, true, false, false, false),
  ('beef stock', array['beef broth','beef stock cube'], 'pantry', 'ml', 1.0, null, null, true, 365, 'ml', 1000, false, true, false, false, false),
  ('vegetable stock', array['vegetable broth','veg stock'], 'pantry', 'ml', 1.0, null, null, true, 365, 'ml', 1000, false, false, false, false, false),
  ('plain flour', array['all purpose flour','flour'], 'pantry', 'g', 0.53, null, null, true, 365, 'g', 1000, false, false, false, false, true),
  ('self raising flour', array['self-raising flour'], 'pantry', 'g', 0.53, null, null, false, 365, 'g', 1000, false, false, false, false, true),
  ('cornflour', array['cornstarch','corn flour'], 'pantry', 'g', 0.55, null, null, true, 540, 'g', 300, false, false, false, false, false),
  ('caster sugar', array['superfine sugar','white sugar','sugar'], 'pantry', 'g', 0.85, null, null, true, 730, 'g', 1000, false, false, false, false, false),
  ('brown sugar', array['light brown sugar','dark brown sugar','soft brown sugar'], 'pantry', 'g', 0.8, null, null, true, 540, 'g', 500, false, false, false, false, false),
  ('honey', array['raw honey'], 'pantry', 'g', 1.42, null, null, true, 730, 'g', 500, false, false, false, false, false),
  ('maple syrup', array['pure maple syrup'], 'pantry', 'ml', 1.32, null, null, false, 365, 'ml', 250, false, false, false, false, false),
  ('rice', array['jasmine rice','basmati rice','long grain rice','white rice'], 'pantry', 'g', 0.85, null, null, true, 730, 'g', 1000, false, false, false, false, false),
  ('arborio rice', array['risotto rice'], 'pantry', 'g', 0.85, null, null, false, 730, 'g', 1000, false, false, false, false, false),
  ('pasta', array['spaghetti','penne','fusilli','rigatoni','dried pasta'], 'pantry', 'g', null, null, null, true, 730, 'g', 500, false, false, false, false, true),
  ('egg noodles', array['hokkien noodles','wheat noodles'], 'pantry', 'g', null, null, null, false, 365, 'g', 400, false, false, false, false, true),
  ('rice noodles', array['vermicelli','pad thai noodles'], 'pantry', 'g', null, null, null, false, 540, 'g', 250, false, false, false, false, false),
  ('couscous', '{}', 'pantry', 'g', 0.72, null, null, false, 540, 'g', 500, false, false, false, false, true),
  ('quinoa', '{}', 'pantry', 'g', 0.75, null, null, false, 540, 'g', 500, false, false, false, false, false),
  ('rolled oats', array['oats','porridge oats'], 'pantry', 'g', 0.4, null, null, true, 365, 'g', 1000, false, false, false, false, true),
  ('red lentils', array['lentils','split red lentils'], 'pantry', 'g', 0.85, null, null, false, 730, 'g', 500, false, false, false, false, false),
  ('chickpeas', array['tinned chickpeas','canned chickpeas','garbanzo beans'], 'pantry', 'g', null, null, null, true, 730, 'g', 400, false, false, false, false, false),
  ('black beans', array['tinned black beans'], 'pantry', 'g', null, null, null, false, 730, 'g', 400, false, false, false, false, false),
  ('kidney beans', array['red kidney beans'], 'pantry', 'g', null, null, null, false, 730, 'g', 400, false, false, false, false, false),
  ('cannellini beans', array['white beans'], 'pantry', 'g', null, null, null, false, 730, 'g', 400, false, false, false, false, false),
  ('peanut butter', array['crunchy peanut butter','smooth peanut butter'], 'pantry', 'g', 1.1, null, null, true, 365, 'g', 500, false, false, false, false, false),
  ('tahini', array['sesame paste'], 'pantry', 'g', 1.05, null, null, false, 365, 'g', 350, false, false, false, false, false),
  ('cashews', array['raw cashews','cashew nuts'], 'pantry', 'g', 0.55, null, null, false, 180, 'g', 250, true, false, false, false, false),
  ('almonds', array['flaked almonds','slivered almonds'], 'pantry', 'g', 0.5, null, null, false, 180, 'g', 250, true, false, false, false, false),
  ('peanuts', array['roasted peanuts'], 'pantry', 'g', 0.6, null, null, false, 180, 'g', 250, true, false, false, false, false),
  ('sesame seeds', array['toasted sesame seeds','white sesame seeds'], 'pantry', 'g', 0.6, null, null, true, 365, 'g', 100, false, false, false, false, false),
  ('baking powder', '{}', 'pantry', 'g', 0.9, null, null, true, 540, 'g', 125, false, false, false, false, false),
  ('bicarb soda', array['baking soda','bicarbonate of soda'], 'pantry', 'g', 0.9, null, null, true, 730, 'g', 125, false, false, false, false, false),
  ('vanilla extract', array['vanilla essence','vanilla'], 'pantry', 'ml', 0.88, null, null, true, 730, 'ml', 50, false, false, false, false, false),
  ('cocoa powder', array['dutch cocoa','unsweetened cocoa'], 'pantry', 'g', 0.42, null, null, false, 540, 'g', 250, false, false, false, false, false),
  ('dark chocolate', array['cooking chocolate','chocolate'], 'pantry', 'g', null, null, null, false, 365, 'g', 180, true, false, false, false, false),
  ('gochujang', array['korean chilli paste'], 'pantry', 'g', 1.2, null, null, false, 365, 'g', 500, false, false, false, false, true),
  ('miso paste', array['white miso','shiro miso'], 'pantry', 'g', 1.2, null, null, false, 365, 'g', 300, false, false, false, false, true),
  ('curry paste', array['red curry paste','green curry paste','thai curry paste'], 'pantry', 'g', 1.1, null, null, false, 365, 'g', 200, false, false, true, false, false),
  ('ginger garlic paste', array['ginger and garlic paste'], 'pantry', 'ml', 1.1, null, null, false, 180, 'ml', 200, false, false, false, false, false),
  ('mirin', '{}', 'pantry', 'ml', 1.05, null, null, false, 730, 'ml', 250, false, false, false, false, false),
  ('shaoxing wine', array['chinese cooking wine','shao xing'], 'pantry', 'ml', 0.99, null, null, false, 730, 'ml', 640, false, false, false, false, true),
  ('olives', array['kalamata olives','green olives','pitted olives'], 'pantry', 'g', null, 4, null, false, 365, 'g', 235, true, false, false, false, false),
  ('capers', array['baby capers'], 'pantry', 'g', null, 1, null, false, 365, 'g', 100, false, false, false, false, false),
  ('gherkins', array['pickles','dill pickles'], 'pantry', 'g', null, 25, null, false, 365, 'g', 500, true, false, false, false, false),
  ('sundried tomatoes', array['semi dried tomatoes'], 'pantry', 'g', null, 5, null, false, 180, 'g', 280, true, false, false, false, false),
  ('nutritional yeast', array['nooch'], 'pantry', 'g', 0.25, null, null, false, 365, 'g', 100, false, false, false, false, false),
  ('salt', array['sea salt','table salt','cooking salt','kosher salt','salt flakes'], 'spice', 'g', 1.2, null, null, true, 1825, 'g', 1000, false, false, false, false, false),
  ('black pepper', array['pepper','cracked pepper','ground black pepper','peppercorns'], 'spice', 'g', 0.5, null, null, true, 730, 'g', 100, false, false, false, false, false),
  ('white pepper', array['ground white pepper'], 'spice', 'g', 0.5, null, null, false, 730, 'g', 50, false, false, false, false, false),
  ('cumin', array['ground cumin','cumin seeds'], 'spice', 'g', 0.45, null, null, true, 540, 'g', 60, false, false, false, false, false),
  ('ground coriander', array['coriander powder','ground coriander seed'], 'spice', 'g', 0.4, null, null, true, 540, 'g', 50, false, false, false, false, false),
  ('turmeric', array['ground turmeric','tumeric'], 'spice', 'g', 0.5, null, null, true, 540, 'g', 50, false, false, false, false, false),
  ('paprika', array['sweet paprika'], 'spice', 'g', 0.45, null, null, true, 540, 'g', 50, false, false, false, false, false),
  ('smoked paprika', array['pimenton'], 'spice', 'g', 0.45, null, null, true, 540, 'g', 50, false, false, false, false, false),
  ('cayenne pepper', array['cayenne','ground cayenne'], 'spice', 'g', 0.45, null, null, true, 540, 'g', 40, false, false, false, false, false),
  ('chilli powder', array['chili powder','chilli flakes','red pepper flakes','dried chilli flakes'], 'spice', 'g', 0.45, null, null, true, 540, 'g', 50, false, false, false, false, false),
  ('garam masala', '{}', 'spice', 'g', 0.42, null, null, true, 365, 'g', 60, false, false, false, false, false),
  ('curry powder', array['madras curry powder'], 'spice', 'g', 0.42, null, null, false, 365, 'g', 60, false, false, false, false, false),
  ('fenugreek', array['kasuri methi','dried fenugreek leaves','fenugreek seeds'], 'spice', 'g', 0.4, null, null, false, 540, 'g', 50, false, false, false, false, false),
  ('cinnamon', array['ground cinnamon','cinnamon stick'], 'spice', 'g', 0.45, null, null, true, 730, 'g', 50, false, false, false, false, false),
  ('nutmeg', array['ground nutmeg'], 'spice', 'g', 0.5, null, null, false, 730, 'g', 40, false, false, false, false, false),
  ('cardamom', array['ground cardamom','cardamom pods'], 'spice', 'g', 0.4, null, null, false, 540, 'g', 30, false, false, false, false, false),
  ('cloves', array['ground cloves','whole cloves'], 'spice', 'g', 0.45, null, null, false, 730, 'g', 30, false, false, false, false, false),
  ('star anise', '{}', 'spice', 'each', null, 1, null, false, 730, 'g', 25, false, false, false, false, false),
  ('bay leaves', array['bay leaf','dried bay leaves'], 'spice', 'each', null, 0.2, null, true, 540, 'g', 5, false, false, false, false, false),
  ('dried oregano', array['oregano'], 'spice', 'g', 0.2, null, null, true, 540, 'g', 30, false, false, false, false, false),
  ('dried thyme', '{}', 'spice', 'g', 0.2, null, null, false, 540, 'g', 25, false, false, false, false, false),
  ('dried rosemary', '{}', 'spice', 'g', 0.2, null, null, false, 540, 'g', 25, false, false, false, false, false),
  ('mixed herbs', array['italian herbs','dried mixed herbs'], 'spice', 'g', 0.2, null, null, true, 540, 'g', 30, false, false, false, false, false),
  ('onion powder', '{}', 'spice', 'g', 0.45, null, null, false, 540, 'g', 50, false, false, false, false, false),
  ('garlic powder', array['granulated garlic'], 'spice', 'g', 0.45, null, null, true, 540, 'g', 50, false, false, false, false, false),
  ('mustard powder', array['dry mustard','english mustard powder'], 'spice', 'g', 0.45, null, null, false, 540, 'g', 50, false, false, false, false, false),
  ('chinese five spice', array['five spice'], 'spice', 'g', 0.42, null, null, false, 540, 'g', 40, false, false, false, false, false),
  ('za''atar', array['zaatar'], 'spice', 'g', 0.35, null, null, false, 365, 'g', 50, false, false, false, false, true),
  ('sumac', array['ground sumac'], 'spice', 'g', 0.4, null, null, false, 365, 'g', 50, false, false, false, false, false),
  ('dukkah', '{}', 'spice', 'g', 0.4, null, null, false, 180, 'g', 100, false, false, false, false, false),
  ('saffron', array['saffron threads'], 'spice', 'g', 0.2, null, null, false, 730, 'g', 1, false, false, false, false, false),
  ('mustard seeds', array['black mustard seeds','yellow mustard seeds'], 'spice', 'g', 0.6, null, null, false, 730, 'g', 50, false, false, false, false, false),
  ('fennel seeds', '{}', 'spice', 'g', 0.4, null, null, false, 730, 'g', 40, false, false, false, false, false),
  ('caraway seeds', '{}', 'spice', 'g', 0.45, null, null, false, 730, 'g', 40, false, false, false, false, false),
  ('allspice', array['ground allspice','pimento'], 'spice', 'g', 0.45, null, null, false, 730, 'g', 40, false, false, false, false, false),
  ('ras el hanout', '{}', 'spice', 'g', 0.42, null, null, false, 365, 'g', 50, false, false, false, false, false),
  ('stock powder', array['chicken salt','vegeta','stock cube'], 'spice', 'g', 0.6, null, null, false, 540, 'g', 120, false, false, false, false, false),
  ('frozen peas', array['peas','garden peas'], 'frozen', 'g', 0.65, null, null, true, 365, 'g', 500, true, false, false, false, false),
  ('frozen corn', array['corn kernels'], 'frozen', 'g', 0.65, null, null, false, 365, 'g', 500, true, false, false, false, false),
  ('frozen spinach', '{}', 'frozen', 'g', 0.8, null, null, false, 365, 'g', 250, true, false, false, false, false),
  ('frozen berries', array['mixed berries','frozen raspberries'], 'frozen', 'g', 0.6, null, null, false, 365, 'g', 500, true, false, false, false, false),
  ('ice cream', array['vanilla ice cream'], 'frozen', 'ml', 0.55, null, null, false, 180, 'ml', 1000, false, false, false, true, false),
  ('frozen chips', array['oven chips','potato chips frozen'], 'frozen', 'g', 0.55, null, null, false, 365, 'g', 1000, true, false, false, false, false),
  ('white wine', array['dry white wine','cooking wine'], 'drinks', 'ml', 0.99, null, null, false, 365, 'ml', 750, false, false, false, false, false),
  ('red wine', array['dry red wine'], 'drinks', 'ml', 0.99, null, null, false, 365, 'ml', 750, false, false, false, false, false),
  ('beer', array['lager','pale ale'], 'drinks', 'ml', 1.0, null, null, false, 180, 'ml', 375, false, false, false, false, true),
  ('water', array['cold water','boiling water','warm water'], 'pantry', 'ml', 1.0, null, null, true, null, 'ml', 1000, false, false, false, false, false),
  ('ice', array['ice cubes'], 'frozen', 'g', 0.92, null, null, false, null, 'g', 2000, true, false, false, false, false)
on conflict (canonical_name) do nothing;

-- ============================================================
-- Sanity checks — run these after seeding
-- ============================================================

-- Every fixture ingredient should resolve above 0.75.
-- select * from match_ingredient('tumeric');
-- select * from match_ingredient('ground pork');
-- select * from match_ingredient('green onions, thinly sliced');
-- select * from match_ingredient('heavy whipping cream');
-- select * from match_ingredient('boneless skinless chicken thighs');

-- Staple coverage drives cook_from_stock ranking quality.
-- select category, count(*) filter (where is_staple) as staples, count(*)
-- from ingredients group by category order by category;

-- Anything volume-measured without a density can't convert to grams.
-- select canonical_name from ingredients
-- where g_per_ml is null and default_unit = 'ml';
